### ISSUE TITLE
Comentarios Entrega 2

### ISSUE THREAD

**Issue by PalumboN** [mnigliazzo/qmp-grupo10#5]
Hola @jlsuh (y el resto que lea esto) , cómo va? Dejo algunos comentarios sobre [tu solución](https://github.com/mnigliazzo/qmp-grupo10/tree/jlsuh-iteracion2-qmp) de la entrega 2 de QMP del viernes pasado, disculpá la demora.

- OJO con el factory. Creo que lo hablaron en clase igual. Pero no deberían ser los Factories los que saben crear las partes de cada Uniforme? Ahora eso está en las subclases de Uniforme (como que cada uno sabe crearse a sí mismo). En realidad la instanciación es fácil, porque no se le pasa nada por constructor, así que no sé cuánto sentido tiene todo esto. También faltaría un lugar general donde usar los factories. Igual fue bueno el intento y la esencia está.

- Cuidado con definir los setter y getters de todos los atributos. Recordar siempre hacerlo a consciencia.

- OJO con los enums anidados, puede llevar a declaraciones redundantes. Creo que también lo mencionaron en clase.

- El diagrama está muy bien y los tests también. Se podría complementar con prosa explicando de manera general cómo se resuelve cada requerimiento. 

> Por último, este comentario creo que es de la entrega pasada pero igual lo aclaro:
https://github.com/mnigliazzo/qmp-grupo10/blob/d1939bbad3494bbc8a6ff63ea9933e4d2096e814/src/main/java/domain/prenda/TipoPrenda.java#L9-L12

OJO que _cohesión_ es la capacidad que tiene un componente de resolver una única cosa. Se dice que mientras _más cosas sepa_ hacer un componente es _menos cohesivo_. Creo que lo que vos querés decir ahí es sobre _consistencia_ o _redundancia_ de datos. Tampoco entiendo bien cómo se relaciona con los "cambios constantes".

Comento esto último porque son las clases de justificaciones que me gustaría entrenar para el parcial. Acá ya te estás animando y está piola, hay que seguirlas trabajando. Tengan siempre a mano el apunte de _cualidades_ del diseño para esto, es clave.

Saludos!

**Comment by EMazzaglia** [comment]
Hola @PalumboN todo bien? Primeramente gracias por la corrección. Quizás para que entiendas como estamos trabajando (no se si lo mencionamos), estamos mergeando a main la solución con la iteración 2, por lo que lo que esta ahí es la solución grupal. Además en cada branch estamos implementando cada uno por separado la solución como nos parece. 
Por alguna razón hiciste comentarios sobre la de @jlsuh? 
Muchas gracias nuevamente. Saludos! 💯

**Comment by PalumboN** [comment]
Hola @EMazzaglia,

Sí lo sé, y lo hice apropósito porque queremos aprovechar estos ejercicios semanales para dar un feedback **individual** sobre cómo vienen. Esto está pensado para que cada estudiante individualmente pueda tener una corrección personalizada de su trabajo antes del parcial.

Si quieren seguir trabajando en grupo no hay ningún problema, solo recuerden subir c/u su propia versión de lo que decidieron en grupo así todxs pasan por esa experiencia :)

Saludos!

**Comment by EMazzaglia** [comment]
:D Muchas gracias por la info! ajja quería avisar por las dudas. 
Saludos! 👯
